#' Load packages
library(tidyr)
library(dplyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(here)
library(readr)
library(janitor)
library(lme4)
library(lmerTest)
library(broom)
library(igraph)
library(tibble)
library(FrF2)
library(future)
library(MOODE)
library(patchwork)
library(gt)

options(knitr.kable.NA = '')