# Summary {.unnumbered}

In Week 4, we have introduced two areas of active research in design of experiments, that build directly on core material from earlier weeks. Both topics, treatment inference and multi-objective design, reduce to some extent the reliance of experimental design methodologies on assumptions that may be unrealistic in many cases. Clearly, these two topics could also be combined. e.g., multi-objective designs could be sought for networked experiments to estimate both direct and indirect treatment effects.

These topics also intersect with other currently trending research areas in design of experiments. The design and analysis of experiments on networks is also an active area within the causal inference community [e.g., @hh2012]; a [workshop](https://vkstats.github.io/dane2024) was held at King's in the summer of 2024. The approach taken by this community tends to differ somewhat from that outlined here, and makes more use of randomisation-based inference. However, many of the issues and objectives are similar.

Increasingly, experiments are taking place on very large networks, particularly online experimentation e.g., on social media [e.g., @nbct2020]. Direct application of the methods in @sec-network will usually be prohibitively computationallyn expensive in such cases. Connections can be made to methods for subsampling large data using design of experiments principles, e.g., @yay2024.   
